name: project_ujikom
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment: 
  sdk: '>=2.19.0 <3.0.0'

dependencies: 
  cupertino_icons: ^1.0.2
  flutter: 
    sdk: flutter
  lottie: ^2.2.0
  hexcolor: ^3.0.1
  dio: ^5.0.0
  get_storage: ^2.0.3
  http: ^0.13.5
  google_fonts: ^4.0.3
  get: ^4.6.5

dev_dependencies: 
  flutter_lints: 2.0.1
  flutter_test: 
    sdk: flutter

flutter: 
  uses-material-design: true

